apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: neat
spec:
  version: "v2.0.1"
  shortDescription: Remove clutter from Kubernetes manifests to make them more readable.
  homepage: https://github.com/itaysk/kubectl-neat
  description: |
    If you try to `kubectl get` resources you have just created,
    they be unreadably verbose. `kubectl-neat` cleans that up by
    removing default values, runtime information, and other internal fields.
    Examples:
    `$ kubectl get pod mypod -o yaml | kubectl neat`
    `$ kubectl neat get -- pod mypod -o yaml`
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/itaysk/kubectl-neat/releases/download/v2.0.1/kubectl-neat_darwin.tar.gz
      sha256: ${sha256}
      files:
        - from: "/*"
          to: "."
      bin: "./kubectl-neat"
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/itaysk/kubectl-neat/releases/download/v2.0.1/kubectl-neat_linux.tar.gz
      sha256: ${sha256}
      files:
        - from: "/*"
          to: "."
      bin: "./kubectl-neat"